name: ML CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install mlflow scikit-learn pandas cloudpickle
      - name: Run MLflow Project
        run: mlflow run Workflow-CI/MLProject --env-manager=local
      
      # Simpan artifak
      - name: Archive MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-results
          path: mlruns/  


      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          
          MODEL_URI=$(find mlruns -type d -name "model" | head -n 1)
          cp -r $MODEL_URI/* Workflow-CI/MLProject/
          
          docker build -t ${{ secrets.DOCKER_USERNAME }}/used-car-model Workflow-CI/MLProject/
          
          docker push ${{ secrets.DOCKER_USERNAME }}/used-car-model


        